# Generated by Django 2.1.7 on 2019-08-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipant',
            name='channel_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]